apiVersion: v1 # Versi API Kubernetes yang digunakan.
kind: Service # Jenis objek Kubernetes yang akan dibuat.
metadata:
  name: karsajobs-service # Nama Service.
  labels:
    app: karsajobs # Label aplikasi.
    tier: backend # Label tier.
spec:
  selector:
    app: karsajobs # Selector pod berdasarkan label app.
    tier: backend # Selector pod berdasarkan label tier.
  type: NodePort  # Jenis Service yang digunakan adalah NodePort.
  ports:
    - port: 8080 # Port yang akan digunakan oleh Service.
      targetPort: 8080
      nodePort: 31001 # Custom Port pada node host yang akan digunakan oleh Service.